name: Android

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  android:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Dependencies
        run: |
          sudo apt -qq update
          sudo apt -qq install -y ninja-build --no-install-recommends --no-install-suggests

      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S $GITHUB_WORKSPACE -B build \
          -GNinja \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-27 \
          -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build/
