name: Linux

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  linux-ubuntu-24_04:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-12
          - g++-13
          - g++-14
          - clang++-16
          - clang++-17
          - clang++-18
        build_type: [Debug, Release]

    runs-on: ubuntu-24.04

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@v5

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-ubuntu-22_04:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang++-13
          - clang++-14
          - clang++-15
        build_type: [Debug, Release]

    runs-on: ubuntu-22.04

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@v5

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-gcc-extra:
    strategy:
      fail-fast: false
      matrix:
        flags: ["-fno-rtti", "-fno-exceptions"]
        build_type: [Debug, Release]

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@v5

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.flags }}"

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-clang-extra:
    strategy:
      fail-fast: false
      matrix:
        flags: ["-fno-rtti", "-fno-exceptions", "-fms-extensions"]
        build_type: [Debug, Release]

    runs-on: ubuntu-24.04

    env:
      CXX: clang++

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@v5

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.flags }}"

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
