name: macOS

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        include:
          - llvm: 15
            build_type: Debug
            os: macos-14
          - llvm: 15
            build_type: Release
            os: macos-14
          - llvm: 14
            build_type: Debug
            os: macos-13
          - llvm: 14
            build_type: Release
            os: macos-13
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_CXX_COMPILER=clang++-${{ matrix.llvm }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
