name: macOS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        include:
          - llvm: 15
            build_type: Debug
            os: macos-14
          - llvm: 15
            build_type: Release
            os: macos-14
          - llvm: 14
            build_type: Debug
            os: macos-13
          - llvm: 14
            build_type: Release
            os: macos-13
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        brew update
        brew install llvm@${{ matrix.llvm }}
        brew install ninja

    - name: Configure CMake
      run: |
        brew --prefix llvm@${{ matrix.llvm }}
        cmake -S $GITHUB_WORKSPACE -B build \
          -GNinja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=$(brew --prefix llvm@${{ matrix.llvm }})/bin/clang-${{ matrix.llvm }} \
          -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@${{ matrix.llvm }})/bin/clang-${{ matrix.llvm }}

    - name: Build project
      run: cmake --build build/

    - name: Run tests
      working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
