name: Windows

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  vs2022:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Configure Visual Studio Environment
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Configure CMake
      run: cmake $GITHUB_WORKSPACE -G "Ninja" -B build

    - name: Build project
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests
      working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  vs2022-clang:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - run: cmake -E make_directory build

    - shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 17 2022" -T ClangCL

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  vs2019:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - run: cmake -E make_directory build

    - shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019"

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  vs2019-clang:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - run: cmake -E make_directory build

    - shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -T ClangCL

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
