name: Windows

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  windows-2022-msvc:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Configure Visual Studio Environment
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Configure CMake
      run: cmake ${{ github.workspace }} -G "Ninja" -B build

    - name: Build project
      run: cmake --build ${{ github.workspace }}\build --config ${{ matrix.build_type }}

    - name: Run tests
      working-directory: ${{ github.workspace }}\build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  windows-2022-clang:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Configure Visual Studio Environment
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} -B build -G "Ninja" -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe

    - name: Build project
      run: cmake --build ${{ github.workspace }}\build --config ${{ matrix.build_type }}

    - working-directory: ${{ github.workspace }}\build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  windows-2019-msvc:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - run: cmake -E make_directory build

    - shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019"

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure

  windows-2019-clang:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - run: cmake -E make_directory build

    - shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -T ClangCL

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
